# Site settings
title: Intellity
email:
description: > # this means to ignore newlines until "baseurl:"
  We design and develop premium software that transforms businesses, optimizes their operations and defines how they engage with customers.
  We, at Intellity, help uplift your brand to online success – from web design to digital marketing. Through our strategical design approach and innovative tools, we help businesses leave their mark online. .
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://intellity.ca" # the base hostname & protocol for your site

# User setting
owner:
email:
facebook_username:
twitter_username:
github_username: intellity
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright: Intellity

# API settings
google_api_key:

# Build settings
markdown: kramdown
